import {Navbar} from '@/components/Navbar';
import './globals.css';
import type {Metadata} from 'next';
import {Space_Mono} from 'next/font/google';
import {Footer} from '@/components/Footer';
import Providers from '@/context/ReactQueryContext';
import {SearchNasaProvider} from '@/context/SearchNasaContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const space_m = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-space_m',
});

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${space_m.className} flex flex-col min-h-screen bg-gray-800`}>
        <Providers>
          <SearchNasaProvider>
            <Navbar />
            {children}
            <Footer />
            <div id="modal-root"></div>
          </SearchNasaProvider>
        </Providers>
      </body>
    </html>
  );
}
